title: GitHub Expert Services Offerings Site Feed
email: contact@github.com
description: A feed for expert services offerings that live on github.com/services
twitter_username: github
github_username:  github

# Build settings
markdown: kramdown

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-octicons

sass:
  style: :compressed
  # Where you keep your scss files
  sass_dir: assets/css/
  # Where sass should look for other scss
  load_paths:
    - _sass
    - node_modules

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - .bundle
  - .git
  - Brewfile
  - CNAME
  - CODEOWNERS
  - Gemfile
  - Gemfile.lock
  - README.md
  - Rakefile
  - bin
  - vendor
  - node_modules
  - package.json
  - package-lock.json
  - script

webrick:
  headers:
    Access-Control-Allow-Origin: "*"

collections:
  offerings:
    output: true
    permalink: /:collection/:path/

defaults:
  - scope:
      path: ""
      type: "offerings"
    values:
      layout: "default"
